package enums;

public enum Model {
	
	GOLF, PASSAT, POLO, CADDY, SHARAN, 
	OCTAVIA, RAPID, SUPERB, FABIA, YETI,
	A4, A5, A6, Q7, S6,
	AURIS, CAMRY, COROLLA, YARIS, AVENSIS,
	C_W205, E_WV213, S_W220, SLK_R172, GLK,
	CORSA, ASTRA, MOKKA, INSIGNIA, MERIVA,
	CHALLENGER, GRAND_CARAVAN, RAM, CALIBER, DAKOTA

}
